# Generated by Django 4.1 on 2023-01-20 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="preRecord",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.CharField(blank=True, max_length=150)),
                ("password", models.CharField(blank=True, max_length=30)),
                ("created", models.DateField(auto_now=True)),
            ],
            options={
                "verbose_name": "Pré Registros",
                "verbose_name_plural": "Pré Registros",
            },
        ),
        migrations.CreateModel(
            name="myProfile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("amount", models.FloatField(blank=True, default=0, null=True)),
                ("created", models.DateField(auto_now=True)),
                ("password", models.CharField(blank=True, max_length=30)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "meu Perfil",
                "verbose_name_plural": "meus Perfis",
            },
        ),
    ]
