# Generated by Django 4.1 on 2023-01-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="myprofile",
            name="gains",
            field=models.IntegerField(default=0),
        ),
    ]
