# Generated by Django 4.1 on 2023-01-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0003_myprofile_last"),
    ]

    operations = [
        migrations.AddField(
            model_name="myprofile",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
