# Generated by Django 4.1 on 2023-01-28 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0004_myprofile_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="myprofile",
            name="forms_1",
            field=models.BooleanField(default=False),
        ),
    ]
