# Generated by Django 4.1 on 2023-02-01 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0006_prerecord_external_id_prerecord_hash"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prerecord",
            name="hash",
        ),
    ]
