# Generated by Django 4.1 on 2023-02-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0007_remove_prerecord_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="myprofile",
            name="forms_phone",
            field=models.BooleanField(default=False),
        ),
    ]
