# Generated by Django 4.1 on 2023-08-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_myprofile_forms_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='pageConfigurations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('typeConfig', models.CharField(blank=True, max_length=20)),
                ('config', models.CharField(blank=True, max_length=5000)),
            ],
        ),
    ]
