# Generated by Django 4.1 on 2023-08-10 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_pageconfigurations'),
    ]

    operations = [
        migrations.CreateModel(
            name='newVideo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('videocode', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=1000)),
                ('views', models.IntegerField(default=1)),
                ('likes', models.IntegerField(default=1)),
                ('createdAt', models.DateField(blank=True, editable=False, verbose_name=datetime.date.today)),
                ('doublePoints', models.BooleanField()),
                ('valueToGain', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='userViewVideo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('videoId', models.IntegerField()),
                ('userId', models.IntegerField()),
            ],
        ),
    ]
