# Generated by Django 4.1 on 2023-08-14 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_newvideo_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userviewvideo',
            name='likedAt',
            field=models.DateField(blank=True, default=datetime.date.today, editable=False),
        ),
    ]
